Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
recipe = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32',delimiter=',', skiprows = 1)
print(recipe[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('Среднее значение в столбцах ', np.mean(recipe[:,1:],0))
print('Максимальные значения в столбцах ',np.max(recipe[:,1:],0))
print('Минимальные значения в столбцах ',np.min(recipe[:,1:],0))
print('Медиана в столбцах ', np.median(recipe[:,1:],0))

Среднее значение в столбцах  [2.16010017e+04 9.05528000e+00]
Максимальные значения в столбцах  [2147483647         39]
Минимальные значения в столбцах  [0 1]
Медиана в столбцах  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
max_time = np.quantile(recipe[:,1], 0.75, axis = 0)
print(max_time)
print(recipe[recipe[:,1]<=max_time])


65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
num_zero = np.count_nonzero(recipe[:,1] == 0)
print(num_zero)
recipe[recipe[:,1]==0] = 1
print( np.count_nonzero(recipe[:,1] == 0))

716
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
unique = np.unique(recipe[:,0])
print(len(unique))

99285


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
unique, num = np.unique(recipe[:,2], return_counts=True)
print(np.column_stack((unique, num)))
print(len())

[[    1   729]
 [    2   872]
 [    3  2821]
 [    4  5435]
 [    5  7845]
 [    6  9315]
 [    7 10568]
 [    8 10874]
 [    9 10539]
 [   10  9545]
 [   11  8260]
 [   12  6572]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1236]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   104]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
array = recipe[recipe[:,2]<=5]
new_array = np.copy(array)
print(new_array)
print('\n\n',recipe)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
mean_ingred = recipe[:,2]/recipe[:,1]
print('Количество ингридиентов на одну минуту\n', mean_ingred)
print('Максимальное значение этой величины для всего датасета\n', max(mean_ingred))


Количество ингридиентов на одну минуту
 [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Максимальное значение этой величины для всего датасета
 14.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
length_top_100_indexes = recipe[:,1].argsort()
length_top_100 = recipe[length_top_100_indexes][-100:]
#print('Топ-100 рецептов с наибольшей продолжительностью\n', length_top_100)
print('Среднее кол-во ингридиентов для топ-100 рецептов\n', np.mean(length_top_100[:,2], axis = 0))

Среднее кол-во ингридиентов для топ-100 рецептов
 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
indexes = np.random.randint(recipe.shape[0], size = 10)
print(recipe[indexes])

[63583 97569 87295 25600 61133 13310 84896 38261 19891  3650]
[[ 13665     20      4]
 [ 68088     30      9]
 [228465     65      6]
 [140139    145     11]
 [145792     50      5]
 [354786     17      5]
 [ 36018     70      8]
 [217296     65     10]
 [241458     40      7]
 [180793     80      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
mean_n_ingr = np.mean(recipe[:,2], axis = 0)
print(recipe[recipe[:,2]<mean_n_ingr])
print('Процент рецептов, кол-во ингредиентов в которых меньше среднего')
print((100*len(recipe[recipe[:,2]<mean_n_ingr]))/len(recipe))

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]
Процент рецептов, кол-во ингредиентов в которых меньше среднего
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
new_recipe = np.append(recipe, np.zeros((recipe.shape[0],1), dtype = 'int32'), axis = 1)
new_recipe[np.logical_and(new_recipe[:,1]<=20,new_recipe[:,2]<=5)] = 1
new_recipe = new_recipe.copy()
print(new_recipe)

100000
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
print((100*len(new_recipe[new_recipe[:,3] == 1]))/len(recipe))

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
group1 = recipe[recipe[:,1]<10]
group2 = recipe[np.logical_and(recipe[:,1]>=10, recipe[:,1]<20)]
group3 = recipe[recipe[:,1]>=20]
max_num = min(len(group1), len(group2), len(group3))
recipe_3d = np.array([[group1[:max_num-1],group2[:max_num-1],group3[:max_num-1]]])
print(recipe_3d)

[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [  2778      0     11]
   [420725      5      3]
   [  4747      0      9]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [107094     10      4]
   [  9831     15      7]
   [335859     12     14]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [ 92137     80      9]
   [168901     25      7]
   [392339     35     13]]]]
